### ISSUE TITLE
Support multiple --pattern, or maybe --include & --exclude

### ISSUE THREAD

**Issue by iiroj** [denis-fatkhudinov/s3-redeploy#2]
Thank you for this awesome tool!

I think it would be more powerful if one was able to supply multiple `--pattern` arguments, or alternatively both an `--include` and `--exclude`. These can be supplied directly to `glob` like so: `glob(include, { exclude })`.

Currently I have it working nicely, but am forced to split the deployment into multiple calls (mostly because of different cache settings): https://github.com/iiroj/iiro.fi/blob/325cb088390caf5743147e1cb520d6f9faa369b4/scripts/deploy.sh

**Comment by btrdnch** [comment]
Hey @iiroj 
Thank you for your attention to the tool, I appreciate that. Let me take a look at the case. At the moment I am a bit overheated on my project but I'll do my best to review the suggestion ASAP

**Comment by btrdnch** [comment]
Hey @iiroj. Sorry for the delay, I was out of the city.
Basically, `s3-redeploy` aims to be called once during the deployment. This way it can store a helper file to S3 bucket and make the deployment faster and more efficient. In general, it means all the files you are deploying (according to the pattern) have the same metadata (like cache, immutability, etc). As you apply different `cache`, `immutable`, etc. parameters for different patterns, having several calls to the utility is convenient. 
In order to do what you've described in a single call and get advantage of the helper file, an ability to use a config file instead of command line arguments should be introduced. There we'd be able to group parameters under a certain pattern. It means you'd have to build or store a parameters object of a certain format and supply it on the utility call.

Did I get you correctly?

**Comment by iiroj** [comment]
Hello,

you understood my request pretty well. A configuration map of some sort, where you could set a cache/header configuration for individual glob patterns would do the job.

----

As an alternative approach, if the the remove behaviour also respected the pattern by not touching any files not matching the given pattern, it would be easier to handle. In my script, I have to use `--no-rm` in all subsequent calls, so that they do not clear out all other files.

I believe this is how the official Python AWS SDK's S3 sync works. If you sync only files matching `*.html` and use the `--delete` flag, it will not consider any files non-html files for deletion. https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

In any case, I opted to deploy to Netlify instead of S3 for lower costs, so this is no longer an issue for me.
